import { Routes } from '@angular/router';
import { Practical1 } from './practical-1/practical-1';
import { Pra2 } from './pra2/pra2';
import { Pra3 } from './pra3/pra3';
import { Pra4 } from './pra4/pra4';
import { Pra5 } from './pra5/pra5';
import { Pra6 } from './pra6/pra6';
import { Pra7 } from './pra7/pra7';
import { Pra8 } from './pra8/pra8';
import { Pra9 } from './pra9/pra9';
import { Pra10 } from './pra10/pra10';
import { Pra11 } from './pra11/pra11';
import { Pra12 } from './pra12/pra12';
import { Pra13 } from './pra13/pra13';
import { Pra14 } from './pra14/pra14';
import { Pra15 } from './pra15/pra15';
import { Pra16 } from './pra16/pra16';
import { Pra17 } from './pra17/pra17';
import { Pra18 } from './pra18/pra18';
import { Pra19 } from './pra19/pra19';
import { Pra19dynamicrouter } from './pra19dynamicrouter/pra19dynamicrouter';

export const routes: Routes = [
  { path: 'pra1', component: Practical1 },
  { path: 'pra2', component: Pra2 },
  { path: 'pra3', component: Pra3 },
  { path: 'pra4', component: Pra4 },
  { path: 'pra5', component: Pra5 },
  { path: 'pra6', component: Pra6 },
  { path: 'pra7', component: Pra7 },
  { path: 'pra8', component: Pra8 },
  { path: 'pra9', component: Pra9 },
  { path: 'pra10', component: Pra10 },
  { path: 'pra11', component: Pra11 },
  { path: 'pra12', component: Pra12 },
  { path: 'pra13', component: Pra13 },
  { path: 'pra14', component: Pra14 },
  { path: 'pra15', component: Pra15 },
  { path: 'pra16', component: Pra16 },
  { path: 'pra17', component: Pra17 },
  { path: 'pra18', component: Pra18 },
  { path: 'pra19', component: Pra19 },
  { path: 'pra19dynamicroute/:id/:name', component: Pra19dynamicrouter },
];
